/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfete;

import Clasele.Proprietar;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import static java.lang.System.err;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/**
 *
 * @author Dya_Bia
 */
public class FerProprietar extends javax.swing.JFrame{

     Connection con;
            Statement st;
            ResultSet rs;
            int cur = 0;
    private int curRow;
    /**
     * Creates new form FerProprietar
     */
    public FerProprietar() {
        initComponents();
        DoConnect();
    }
    public void DoConnect()
    {
        try{
            String host="jdbc:derby://localhost:1527/Georgiana";
            String uName="Georgiana";
            String uPass="55555";
            
         
           Connection con=DriverManager.getConnection(host,uName, uPass);
           
           
            st=con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String sql="select * from PROPRIETAR ";
            rs =st.executeQuery(sql);
            
            //rs.previous();
            rs.next();
    
            String nume=rs.getString("NumeProp");
            String prenume=rs.getString("PrenumeProp");
            String ziua=rs.getString("ZiuaN");
            String luna=rs.getString("LunaN");
            String an=rs.getString("AnulN");
            String strada=rs.getString("Strada");
            String numar=rs.getString("Numar");
            String etaj=rs.getString("Etaj");
            String bloc=rs.getString("Bloc");
            String scara=rs.getString("Scara");
            String apartament=rs.getString("NumarApartament");
            String localitate=rs.getString("Localitate");
            String judet=rs.getString("Judet");
            String tara=rs.getString("Tara");
            String mail=rs.getString("AdresaMail");
            String telefon=rs.getString("Telefon");
            
            
            jTextField1.setText(nume);
            jTextField2.setText(prenume);
            jTextField3.setText(ziua);
            jTextField4.setText(luna);
            jTextField5.setText(an);
            jTextField6.setText(strada);
            jTextField7.setText(numar);
            jTextField8.setText(etaj);
            jTextField9.setText(bloc);
            jTextField10.setText(scara);
            jTextField11.setText(apartament);
            jTextField12.setText(localitate);
            jTextField13.setText(judet);
            jTextField14.setText(tara);
            jTextField15.setText(mail);
            jTextField16.setText(telefon);
                      
        }
    catch( SQLException err){
           //JOptionPane.showMessageDialog(err.getMessage());
        System.out.println(err.getMessage());
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("NumeProp");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 40, 50, 13);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(250, 20, 159, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("PrenumeProp");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 70, 64, 13);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(250, 50, 159, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("ZiuaN");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(201, 95, 28, 13);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(250, 80, 159, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("LunaN");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(198, 121, 31, 13);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(250, 110, 159, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("AnulN");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(199, 147, 30, 13);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(250, 140, 159, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Strada");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(200, 180, 28, 13);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(250, 170, 157, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Numar");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(200, 210, 31, 13);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(250, 200, 43, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("Etaj");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(310, 210, 19, 13);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(340, 200, 60, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Bloc");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(210, 240, 21, 13);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(250, 230, 43, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setText("Scara");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(310, 240, 24, 13);
        getContentPane().add(jTextField10);
        jTextField10.setBounds(340, 230, 61, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 255));
        jLabel11.setText("Numarapartament");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(150, 270, 84, 13);
        getContentPane().add(jTextField11);
        jTextField11.setBounds(250, 260, 43, 30);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 255));
        jLabel12.setText("Localitate");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(190, 300, 47, 13);
        getContentPane().add(jTextField12);
        jTextField12.setBounds(250, 290, 158, 30);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 255));
        jLabel13.setText("Judet");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(210, 330, 23, 13);
        getContentPane().add(jTextField13);
        jTextField13.setBounds(250, 320, 158, 30);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 255));
        jLabel14.setText("Tara");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(210, 360, 22, 13);
        getContentPane().add(jTextField14);
        jTextField14.setBounds(250, 350, 158, 30);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 255));
        jLabel15.setText("Adresamail");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(190, 390, 51, 13);
        getContentPane().add(jTextField15);
        jTextField15.setBounds(250, 380, 158, 30);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 51, 204));
        jLabel16.setText("Telefon");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(200, 420, 37, 13);
        getContentPane().add(jTextField16);
        jTextField16.setBounds(250, 410, 158, 30);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 255));
        jLabel17.setText("Adresa");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(160, 180, 31, 13);

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setFont(new java.awt.Font("Script MT Bold", 0, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setText("Primul");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 450, 65, 23);

        jButton2.setBackground(new java.awt.Color(153, 255, 255));
        jButton2.setFont(new java.awt.Font("Script MT Bold", 0, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 255));
        jButton2.setText("Precedentul");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(120, 450, 83, 23);

        jButton3.setBackground(new java.awt.Color(153, 255, 255));
        jButton3.setFont(new java.awt.Font("Script MT Bold", 0, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 255));
        jButton3.setText("Urmatorul");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(230, 450, 81, 23);

        jButton4.setBackground(new java.awt.Color(153, 255, 255));
        jButton4.setFont(new java.awt.Font("Script MT Bold", 0, 11)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 255));
        jButton4.setText("Ultimul");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(350, 450, 69, 23);

        jButton5.setBackground(new java.awt.Color(153, 255, 255));
        jButton5.setFont(new java.awt.Font("Script MT Bold", 0, 11)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 255));
        jButton5.setText("Update");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(10, 480, 65, 23);

        jButton6.setBackground(new java.awt.Color(153, 255, 255));
        jButton6.setFont(new java.awt.Font("Script MT Bold", 0, 11)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 255));
        jButton6.setText("Delete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(240, 480, 59, 23);

        jButton7.setBackground(new java.awt.Color(153, 255, 255));
        jButton7.setFont(new java.awt.Font("Script MT Bold", 0, 11)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 0, 255));
        jButton7.setText("New record");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(120, 480, 83, 23);

        jButton8.setBackground(new java.awt.Color(153, 255, 255));
        jButton8.setFont(new java.awt.Font("Script MT Bold", 0, 11)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 0, 255));
        jButton8.setText("Save new record");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(320, 480, 103, 23);

        jButton9.setBackground(new java.awt.Color(153, 255, 255));
        jButton9.setFont(new java.awt.Font("Script MT Bold", 0, 11)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 0, 255));
        jButton9.setText("Cancel");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(10, 510, 61, 23);

        jButton10.setBackground(new java.awt.Color(153, 255, 255));
        jButton10.setFont(new java.awt.Font("Script MT Bold", 0, 11)); // NOI18N
        jButton10.setForeground(new java.awt.Color(0, 0, 255));
        jButton10.setText("Iesire");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(360, 510, 59, 23);

        jLabel19.setBackground(new java.awt.Color(0, 0, 204));
        jLabel19.setFont(new java.awt.Font("Tunga", 3, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 0, 153));
        jLabel19.setText("Actualizare proprietar");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(222, 7, 182, 23);

        jLabel18.setIcon(new javax.swing.ImageIcon("D:\\laptop\\Agenda mea\\DSC_3908.JPG")); // NOI18N
        getContentPane().add(jLabel18);
        jLabel18.setBounds(10, 11, 144, 180);

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dya_Bia\\Desktop\\ground).jpg")); // NOI18N
        getContentPane().add(jLabel20);
        jLabel20.setBounds(0, 0, 440, 530);

        setSize(new java.awt.Dimension(459, 579));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            rs.last();
            String nume=rs.getString("NumeProp");
            String prenume=rs.getString("PrenumeProp");
            String ziua=rs.getString("ZiuaN");
            String luna=rs.getString("LunaN");
            String an=rs.getString("AnulN");
            String strada=rs.getString("Strada");
            String numar=rs.getString("Numar");
            String etaj=rs.getString("Etaj");
            String bloc=rs.getString("Bloc");
            String scara=rs.getString("Scara");
            String apartament=rs.getString("NumarApartament");
            String localitate=rs.getString("Localitate");
            String judet=rs.getString("Judet");
            String tara=rs.getString("Tara");
            String mail=rs.getString("AdresaMail");
            String telefon=rs.getString("Telefon");
            
            
            jTextField1.setText(nume);
            jTextField2.setText(prenume);
            jTextField3.setText(ziua);
            jTextField4.setText(luna);
            jTextField5.setText(an);
            jTextField6.setText(strada);
            jTextField7.setText(numar);
            jTextField8.setText(etaj);
            jTextField9.setText(bloc);
            jTextField10.setText(scara);
            jTextField11.setText(apartament);
            jTextField12.setText(localitate);
            jTextField13.setText(judet);
            jTextField14.setText(tara);
            jTextField15.setText(mail);
            jTextField16.setText(telefon);
            
             }
       
        catch(SQLException err) {
          System.out.println(err.getMessage());
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         try
        {
            if(rs.previous())
            {
                
                String nume=rs.getString("NumeProp");
            String prenume=rs.getString("PrenumeProp");
            String ziua=rs.getString("ZiuaN");
            String luna=rs.getString("LunaN");
            String an=rs.getString("AnulN");
            String strada=rs.getString("Strada");
            String numar=rs.getString("Numar");
            String etaj=rs.getString("Etaj");
            String bloc=rs.getString("Bloc");
            String scara=rs.getString("Scara");
            String apartament=rs.getString("NumarApartament");
            String localitate=rs.getString("Localitate");
            String judet=rs.getString("Judet");
            String tara=rs.getString("Tara");
            String mail=rs.getString("AdresaMail");
            String telefon=rs.getString("Telefon");
            
            
            jTextField1.setText(nume);
            jTextField2.setText(prenume);
            jTextField3.setText(ziua);
            jTextField4.setText(luna);
            jTextField5.setText(an);
            jTextField6.setText(strada);
            jTextField7.setText(numar);
            jTextField8.setText(etaj);
            jTextField9.setText(bloc);
            jTextField10.setText(scara);
            jTextField11.setText(apartament);
            jTextField12.setText(localitate);
            jTextField13.setText(judet);
            jTextField14.setText(tara);
            jTextField15.setText(mail);
            jTextField16.setText(telefon);
                  }
            else
            {
                rs.next();
               // JOptionPane.showMessageDialog(FerProprietar.this, "Start of File");
            }    
        }
        catch(SQLException err) {
          System.out.println(err.getMessage());

       
      
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         try
        {
            if(rs.next())
            {
                 String nume=rs.getString("NumeProp");
            String prenume=rs.getString("PrenumeProp");
            String ziua=rs.getString("ZiuaN");
            String luna=rs.getString("LunaN");
            String an=rs.getString("AnulN");
            String strada=rs.getString("Strada");
            String numar=rs.getString("Numar");
            String etaj=rs.getString("Etaj");
            String bloc=rs.getString("Bloc");
            String scara=rs.getString("Scara");
            String apartament=rs.getString("NumarApartament");
            String localitate=rs.getString("Localitate");
            String judet=rs.getString("Judet");
            String tara=rs.getString("Tara");
            String mail=rs.getString("AdresaMail");
            String telefon=rs.getString("Telefon");
            
            
            jTextField1.setText(nume);
            jTextField2.setText(prenume);
            jTextField3.setText(ziua);
            jTextField4.setText(luna);
            jTextField5.setText(an);
            jTextField6.setText(strada);
            jTextField7.setText(numar);
            jTextField8.setText(etaj);
            jTextField9.setText(bloc);
            jTextField10.setText(scara);
            jTextField11.setText(apartament);
            jTextField12.setText(localitate);
            jTextField13.setText(judet);
            jTextField14.setText(tara);
            jTextField15.setText(mail);
            jTextField16.setText(telefon);
                 }
            else
            {
                rs.previous();
            }    
        }
        catch(SQLException err) {
          System.out.println(err.getMessage());

       
      }
            
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         try{
            rs.last();
            String nume=rs.getString("NumeProp");
            String prenume=rs.getString("PrenumeProp");
            String ziua=rs.getString("ZiuaN");
            String luna=rs.getString("LunaN");
            String an=rs.getString("AnulN");
            String strada=rs.getString("Strada");
            String numar=rs.getString("Numar");
            String etaj=rs.getString("Etaj");
            String bloc=rs.getString("Bloc");
            String scara=rs.getString("Scara");
            String apartament=rs.getString("NumarApartament");
            String localitate=rs.getString("Localitate");
            String judet=rs.getString("Judet");
            String tara=rs.getString("Tara");
            String mail=rs.getString("AdresaMail");
            String telefon=rs.getString("Telefon");
            
            
            jTextField1.setText(nume);
            jTextField2.setText(prenume);
            jTextField3.setText(ziua);
            jTextField4.setText(luna);
            jTextField5.setText(an);
            jTextField6.setText(strada);
            jTextField7.setText(numar);
            jTextField8.setText(etaj);
            jTextField9.setText(bloc);
            jTextField10.setText(scara);
            jTextField11.setText(apartament);
            jTextField12.setText(localitate);
            jTextField13.setText(judet);
            jTextField14.setText(tara);
            jTextField15.setText(mail);
            jTextField16.setText(telefon);
            
            }
       
        catch(SQLException err) {
          System.out.println(err.getMessage());
      }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
           String nume=jTextField1.getText();
            String prenume=jTextField2.getText();
            String ziua=jTextField3.getText();
            String luna=jTextField4.getText();
            String an=jTextField4.getText();
            String strada=jTextField5.getText();
            String numar=jTextField6.getText();
            String etaj=jTextField9.getText();
            String bloc=jTextField8.getText();
            String apartament=jTextField10.getText();
            String mail=jTextField13.getText();
            String telefon=jTextField15.getText();
            String localitate=jTextField11.getText();
            String judet=jTextField3.getText();
            String tara=jTextField14.getText();
   
        try{
          
              rs.updateString( "NumeProp",nume );
              rs.updateString( "PrenumeProp",prenume  );
              rs.updateString( "ZiuaN",ziua );
              rs.updateString( "LunaN",luna  );
              rs.updateString("AnulN" ,an );
              rs.updateString("Strada" , strada );
              rs.updateString( "Numar",numar );
              rs.updateString( "Etaj", etaj );
              rs.updateString( "Bloc",bloc );
              rs.updateString( "Numarapartament",apartament  );
              rs.updateString("AdresaMail" ,mail );
              rs.updateString("Telefon" ,telefon  );
              rs.updateString("Localitate" ,localitate );
              rs.updateString( "Judet",judet  );
              rs.updateString( "Tara", tara );
             
              rs.updateRow( );
            
       }
       catch(SQLException err) {
          System.out.println(err.getMessage());
          }                     
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try{
            rs.deleteRow();
            st.close();
            rs.close();
            st=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                                    ResultSet.CONCUR_UPDATABLE);
            String sql= "SELECT * from PROPRIETAR";
            rs=st.executeQuery(sql);
            
            rs.next();
             String nume=rs.getString("NumeProp");
            String prenume=rs.getString("PrenumeProp");
            String ziua=rs.getString("ZiuaN");
            String luna=rs.getString("LunaN");
            String an=rs.getString("AnulN");
            String strada=rs.getString("Strada");
            String numar=rs.getString("Numar");
            String etaj=rs.getString("Etaj");
            String bloc=rs.getString("Bloc");
            String scara=rs.getString("Scara");
            String apartament=rs.getString("NumarApartament");
            String localitate=rs.getString("Localitate");
            String judet=rs.getString("Judet");
            String tara=rs.getString("Tara");
            String mail=rs.getString("AdresaMail");
            String telefon=rs.getString("Telefon");
            
            jTextField1.setText(nume);
            jTextField2.setText(prenume);
            jTextField3.setText(ziua);
            jTextField4.setText(luna);
            jTextField5.setText(an);
            jTextField6.setText(strada);
            jTextField7.setText(numar);
            jTextField8.setText(etaj);
            jTextField9.setText(bloc);
            jTextField10.setText(scara);
            jTextField11.setText(apartament);
            jTextField12.setText(localitate);
            jTextField13.setText(judet);
            jTextField14.setText(tara);
            jTextField15.setText(mail);
            jTextField16.setText(telefon);
            }
        catch(SQLException err) {
          System.out.println(err.getMessage());
 }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         try{
            
            curRow=rs.getRow();
            
             jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField10.setText("");
            jTextField11.setText("");
            jTextField12.setText("");
            jTextField13.setText("");
            jTextField14.setText("");
            jTextField15.setText("");
            jTextField16.setText("");
            
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);//update,delete, new record
            
            jButton8.setEnabled(true);//salvare
            jButton9.setEnabled(true);//cancel
              }                                         
 catch(SQLException err) {
          System.out.println(err.getMessage());
 }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        String nume=jTextField1.getText();
            String prenume=jTextField2.getText();
            String ziua=jTextField3.getText();
            String luna=jTextField4.getText();
            String an=jTextField4.getText();
            String strada=jTextField5.getText();
            String numar=jTextField6.getText();
            String etaj=jTextField9.getText();
            String bloc=jTextField8.getText();
            String apartament=jTextField10.getText();
            String mail=jTextField13.getText();
            String telefon=jTextField15.getText();
            String localitate=jTextField11.getText();
            String judet=jTextField3.getText();
            String tara=jTextField14.getText();
            
            try {
           rs.moveToInsertRow();
           rs.insertRow();
           rs.updateString( "NumeProp",nume );
              rs.updateString( "PrenumeProp",prenume  );
              rs.updateString( "ZiuaN",ziua );
              rs.updateString( "LunaN",luna  );
              rs.updateString("AnulN" ,an );
              rs.updateString("Strada" , strada );
              rs.updateString( "Numar",numar );
              rs.updateString( "Etaj", etaj );
              rs.updateString( "Bloc",bloc );
              rs.updateString( "Numarapartament",apartament  );
              rs.updateString("AdresaMail" ,mail );
              rs.updateString("Telefon" ,telefon  );
              rs.updateString("Localitate" ,localitate );
              rs.updateString( "Judet",judet  );
              rs.updateString( "Tara", tara );
             
              
              st.close();
              rs.close();
              
              st=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                                    ResultSet.CONCUR_UPDATABLE);
              String sql= "SELECT * from PROPRIETAR";
             rs = st.executeQuery(sql);
             
             String nume1=rs.getString("NumeProp");
            String prenume1=rs.getString("PrenumeProp");
            String ziua1=rs.getString("ZiuaN");
            String luna1=rs.getString("LunaN");
            String an1=rs.getString("AnulN");
            String strada1=rs.getString("Strada");
            String numar1=rs.getString("Numar");
            String etaj1=rs.getString("Etaj");
            String bloc1=rs.getString("Bloc");
            String scara1=rs.getString("Scara");
            String apartament1=rs.getString("NumarApartament");
            String localitate1=rs.getString("Localitate");
            String judet1=rs.getString("Judet");
            String tara1=rs.getString("Tara");
            String mail1=rs.getString("AdresaMail");
            String telefon1=rs.getString("Telefon");
            
            jTextField1.setText(nume1);
            jTextField2.setText(prenume1);
            jTextField3.setText(ziua1);
            jTextField4.setText(luna1);
            jTextField5.setText(an1);
            jTextField6.setText(strada1);
            jTextField7.setText(numar1);
            jTextField8.setText(etaj1);
            jTextField9.setText(bloc1);
            jTextField10.setText(scara1);
            jTextField11.setText(apartament1);
            jTextField12.setText(localitate1);
            jTextField13.setText(judet1);
            jTextField14.setText(tara1);
            jTextField15.setText(mail1);
            jTextField16.setText(telefon1);
            
            jButton1.setEnabled(true);
            jButton2.setEnabled(true);
            jButton3.setEnabled(true);
            jButton4.setEnabled(true);
            jButton5.setEnabled(true);
            jButton6.setEnabled(true);
            jButton7.setEnabled(true);//update,delete, new record
            
            jButton8.setEnabled(false);//salvare
            jButton9.setEnabled(false);//cancel
            }
    
    
        catch(SQLException err) {
          System.out.println(err.getMessage());
                                         
    }          
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        try{
            
            rs.absolute(curRow);
             
              jTextField1.setText(rs.getString("NumeProp"));
            jTextField2.setText(rs.getString("PrenumeProp"));
            jTextField3.setText(rs.getString("ZiuaN"));
            jTextField4.setText(rs.getString("LunaN"));
            jTextField5.setText(rs.getString("AnulN"));
            jTextField6.setText(rs.getString("Srada"));
            jTextField7.setText(rs.getString("Numar"));
            jTextField8.setText(rs.getString("Etaj"));
            jTextField9.setText(rs.getString("Bloc"));
            jTextField10.setText(rs.getString("Scara"));
            jTextField11.setText(rs.getString("NumarApartament"));
            jTextField12.setText(rs.getString("Localitate"));
            jTextField13.setText(rs.getString("Judet"));
            jTextField14.setText(rs.getString("Tara"));
            jTextField15.setText(rs.getString("AdresaMail"));
            jTextField16.setText(rs.getString("Telefon"));
            
              jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);//update,delete, new record
            
            jButton8.setEnabled(true);//salvare
            jButton9.setEnabled(true);//cancel
             }                                         
 catch(SQLException err) {
          System.out.println(err.getMessage());
 }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FerProprietar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FerProprietar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FerProprietar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FerProprietar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FerProprietar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
