/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfete;

import Clasele.Conectare;
import Clasele.Eveniment;
import static java.lang.System.err;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Dya_Bia
 */
public class FEveniment extends javax.swing.JFrame {

            Connection con;
            Statement st;
            ResultSet rs;
            int cur = 0;
    private int curRow;
    private int indice;
            
    /**
     * Creates new form FEveniment
     */
    public FEveniment() {
        initComponents();
        DoConnect();
    }
    public void DoConnect()
    {
        try{
            String host="jdbc:derby://localhost:1527/Georgiana";
            String uName="Georgiana";
            String uPass="55555";
            
         
           Connection con=DriverManager.getConnection(host,uName, uPass);
           
           
            st=con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String sql="select * from EVENIMENTE";
            rs =st.executeQuery(sql);
            
            //rs.previous();
            rs.next();
            int id_col=rs.getInt("ID");
            String id= Integer.toString(id_col);
            String first=rs.getString("TipEveniment");
            String second=rs.getString("LocEveniment");
            String third=rs.getString("ZiuaEveniment");
            String fourth=rs.getString("LunaEveniment");
            String fifth=rs.getString("AnulEveniment");
            String sixth=rs.getString("OraEveniment");
   
            jTextField7.setText(id);
            jTextField1.setText(first);
            jTextField2.setText(second);
            jTextField3.setText(third);
            jTextField4.setText(fourth);
            jTextField5.setText(fifth);
            jTextField6.setText(sixth);
            
            
        }
    catch( SQLException err){
           //JOptionPane.showMessageDialog(err.getMessage());
        System.out.println(err.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 255));
        jLabel1.setText("Evenimente");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 10, 134, 27);

        jLabel2.setFont(new java.awt.Font("Modern No. 20", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setText("TipEveniment");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 86, 81, 13);

        jLabel3.setFont(new java.awt.Font("Modern No. 20", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 153));
        jLabel3.setText("LocEveniment");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 112, 81, 13);

        jLabel4.setFont(new java.awt.Font("Modern No. 20", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 153));
        jLabel4.setText("ZiuaEveniment");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 138, 81, 13);

        jLabel5.setFont(new java.awt.Font("Modern No. 20", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 153));
        jLabel5.setText("LunaEveniment");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 164, 72, 13);

        jLabel6.setFont(new java.awt.Font("Modern No. 20", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 153));
        jLabel6.setText("AnulEveniment");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 190, 71, 13);

        jLabel7.setFont(new java.awt.Font("Modern No. 20", 0, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 153));
        jLabel7.setText("OraEveniment");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 212, 64, 13);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(100, 70, 170, 30);

        jTextField2.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(100, 100, 168, 30);

        jTextField3.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        getContentPane().add(jTextField3);
        jTextField3.setBounds(100, 130, 168, 30);

        jTextField4.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        getContentPane().add(jTextField4);
        jTextField4.setBounds(101, 159, 168, 30);

        jTextField5.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        getContentPane().add(jTextField5);
        jTextField5.setBounds(100, 190, 168, 30);

        jTextField6.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        getContentPane().add(jTextField6);
        jTextField6.setBounds(100, 220, 170, 30);

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setFont(new java.awt.Font("Script MT Bold", 0, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setText("Primul");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 290, 65, 23);

        jButton2.setBackground(new java.awt.Color(153, 255, 255));
        jButton2.setFont(new java.awt.Font("Script MT Bold", 0, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 255));
        jButton2.setText("Precedentul");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(90, 290, 83, 23);

        jButton3.setBackground(new java.awt.Color(153, 255, 255));
        jButton3.setFont(new java.awt.Font("Script MT Bold", 0, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 255));
        jButton3.setText("Urmatorul");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(180, 290, 81, 23);

        jButton4.setFont(new java.awt.Font("Script MT Bold", 0, 11)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 255));
        jButton4.setText("Ultimul");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(280, 290, 69, 23);

        jButton5.setBackground(new java.awt.Color(153, 255, 255));
        jButton5.setFont(new java.awt.Font("Script MT Bold", 0, 11)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 255));
        jButton5.setText("Stergere");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(180, 330, 67, 23);

        jButton6.setBackground(new java.awt.Color(153, 255, 255));
        jButton6.setFont(new java.awt.Font("Script MT Bold", 0, 11)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 255));
        jButton6.setText("Salvare noua");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(260, 330, 93, 23);

        jButton7.setBackground(new java.awt.Color(153, 255, 255));
        jButton7.setFont(new java.awt.Font("Script MT Bold", 0, 11)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 0, 255));
        jButton7.setText("Terminare");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(264, 370, 90, 23);

        jLabel8.setFont(new java.awt.Font("Modern No. 20", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("ID");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 40, 13, 13);

        jTextField7.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        getContentPane().add(jTextField7);
        jTextField7.setBounds(98, 39, 170, 30);

        jButton8.setBackground(new java.awt.Color(153, 255, 255));
        jButton8.setFont(new java.awt.Font("Script MT Bold", 0, 11)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 0, 255));
        jButton8.setText("Update");
        jButton8.setFocusTraversalPolicyProvider(true);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(10, 330, 65, 23);

        jButton10.setBackground(new java.awt.Color(153, 255, 255));
        jButton10.setFont(new java.awt.Font("Script MT Bold", 0, 11)); // NOI18N
        jButton10.setForeground(new java.awt.Color(0, 0, 255));
        jButton10.setText("New record");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(90, 330, 83, 23);

        jButton11.setBackground(new java.awt.Color(153, 255, 255));
        jButton11.setFont(new java.awt.Font("Script MT Bold", 0, 11)); // NOI18N
        jButton11.setForeground(new java.awt.Color(0, 0, 255));
        jButton11.setText("Cancel");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(10, 370, 70, 23);

        jLabel9.setIcon(new javax.swing.ImageIcon("D:\\laptop\\facultate 2013-2014\\organizatori-nunti-371.jpg")); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 380, 410);

        setSize(new java.awt.Dimension(394, 446));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
          setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         try
        {
            if(rs.next())
            {
                int id_col=rs.getInt("ID");
       String id= Integer.toString(id_col);
       String first=rs.getString("TipEveniment");
       String second=rs.getString("LocEveniment");
       String third=rs.getString("ZiuaEveniment");
       String fourth=rs.getString("LunaEveniment");
       String fifth=rs.getString("AnulEveniment");
       String sixth=rs.getString("OraEveniment");
   
       jTextField7.setText(id);
       jTextField1.setText(first);
       jTextField2.setText(second);
       jTextField3.setText(third);
       jTextField4.setText(fourth);
       jTextField5.setText(fifth);
       jTextField6.setText(sixth);
     }
            else
            {
                rs.previous();
            }    
        }
        catch(SQLException err) {
          System.out.println(err.getMessage());

       
      }
    
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       /* ArrayList<Eveniment> even= Conectare.getConnection().getEvenimente();
          if (indice !=1){
          indice--;
          }
         
               
        jTextField7.setText(String.valueOf(even.get(indice).getId()));
       
       jTextField1.setText(even.get(indice).getTipEveniment());
       jTextField2.setText(even.get(indice).getLocEveniment());
       jTextField3.setText(even.get(indice).getZiuaEveniment());
       jTextField4.setText(even.get(indice).getLunaEveniment());
       jTextField5.setText(even.get(indice).getAnulEveniment());
       jTextField6.setText(even.get(indice).getOraEveniment());
       */
         try
        {
            if(rs.previous())
            {
       int id_col=rs.getInt("ID");
       String id= Integer.toString(id_col);
       String first=rs.getString("TipEveniment");
       String second=rs.getString("LocEveniment");
       String third=rs.getString("ZiuaEveniment");
       String fourth=rs.getString("LunaEveniment");
       String fifth=rs.getString("AnulEveniment");
       String sixth=rs.getString("OraEveniment");
   
       jTextField7.setText(id);
       jTextField1.setText(first);
       jTextField2.setText(second);
       jTextField3.setText(third);
       jTextField4.setText(fourth);
       jTextField5.setText(fifth);
       jTextField6.setText(sixth);
     }
            else
            {
                rs.next();
            }    
        }
        catch(SQLException err) {
          System.out.println(err.getMessage());

       
      }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try{
            rs.first();
            int id_col=rs.getInt("ID");
       String id= Integer.toString(id_col);
       String first=rs.getString("TipEveniment");
       String second=rs.getString("LocEveniment");
       String third=rs.getString("ZiuaEveniment");
       String fourth=rs.getString("LunaEveniment");
       String fifth=rs.getString("ZiuaEveniment");
       String sixth=rs.getString("OraEveniment");
   
       jTextField7.setText(id);
       jTextField1.setText(first);
       jTextField2.setText(second);
       jTextField3.setText(third);
       jTextField4.setText(fourth);
       jTextField5.setText(fifth);
       jTextField6.setText(sixth);
        
        }
        catch(SQLException err) {
          System.out.println(err.getMessage());

       
      }
        /*  ArrayList<Eveniment> even= Conectare.getConnection().getEvenimente();
          indice =0;
   
       jTextField7.setText(String.valueOf(even.get(indice).getId()));
       
       jTextField1.setText(even.get(indice).getTipEveniment());
       jTextField2.setText(even.get(indice).getLocEveniment());
       jTextField3.setText(even.get(indice).getZiuaEveniment());
       jTextField4.setText(even.get(indice).getLunaEveniment());
       jTextField5.setText(even.get(indice).getAnulEveniment());
       jTextField6.setText(even.get(indice).getOraEveniment());*/
        
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
          try{
            rs.last();
            int id_col=rs.getInt("ID");
       String id= Integer.toString(id_col);
       String first=rs.getString("TipEveniment");
       String second=rs.getString("LocEveniment");
       String third=rs.getString("ZiuaEveniment");
       String fourth=rs.getString("LunaEveniment");
       String fifth=rs.getString("AnulEveniment");
       String sixth=rs.getString("OraEveniment");
   
       jTextField7.setText(id);
       jTextField1.setText(first);
       jTextField2.setText(second);
       jTextField3.setText(third);
       jTextField4.setText(fourth);
       jTextField5.setText(fifth);
       jTextField6.setText(sixth);
        
        }
        catch(SQLException err) {
          System.out.println(err.getMessage());

       
      }
         /* ArrayList<Eveniment> even= Conectare.getConnection().getEvenimente();
          indice=even.size()-1;
   
       jTextField7.setText(String.valueOf(even.get(indice).getId()));
       
       jTextField1.setText(even.get(indice).getTipEveniment());
       jTextField2.setText(even.get(indice).getLocEveniment());
       jTextField3.setText(even.get(indice).getZiuaEveniment());
       jTextField4.setText(even.get(indice).getLunaEveniment());
       jTextField5.setText(even.get(indice).getAnulEveniment());
       jTextField6.setText(even.get(indice).getOraEveniment());*/
    
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
       String first=jTextField1.getText();
       String second=jTextField2.getText();
       String third=jTextField3.getText();
       String fourth=jTextField4.getText();
       String fifth=jTextField5.getText();
       String sixth=jTextField6.getText();
       String id=jTextField7.getText();
       
       int newID= Integer.parseInt(id);
       try {
              rs.moveToInsertRow();
           
              rs.updateInt( "ID", newID );
              rs.updateString( "TipEveniment", first );
              rs.updateString( "LocEveniment", second );
              rs.updateString( "ZiuaEveniment", third );
              rs.updateString( "LunaEveniment", fourth );
              rs.updateString( "AnulEveniment", fifth );
              rs.updateString( "OraEveniment", sixth );
              
              
              rs.insertRow();
              
              st.close();
              rs.close();
              
              st=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                                    ResultSet.CONCUR_UPDATABLE);
              String sql= "SELECT * from EVENIMENTE";
              rs = st.executeQuery(sql);
            
           rs.next();
            int id_col=rs.getInt("ID");
            String id1=Integer.toString(id_col);
            String first1=rs.getString("TipEveniment");
            String second2=rs.getString("LocEveniment");
            String third3=rs.getString("ZiuaEveniment");
            String fourth4=rs.getString("LunaEveniment");
            String fifth5=rs.getString("AnulEveniment");
            String sixth6=rs.getString("OraEveniment");
            
            jTextField7.setText(id1);
            jTextField1.setText(first1);
            jTextField2.setText(second2);
            jTextField3.setText(third3);
            jTextField4.setText(fourth4);
            jTextField5.setText(fifth5);
            jTextField6.setText(sixth6); 
            
       
       //butoanele pasul 7
       jButton1.setEnabled(true);
       jButton2.setEnabled(true);
       jButton3.setEnabled(true);
       jButton4.setEnabled(true);
       jButton8.setEnabled(true);
       jButton5.setEnabled(true);
       jButton10.setEnabled(true);
       
       jButton6.setEnabled(false);
       jButton11.setEnabled(false);
       
       
       }
    
    
        catch(SQLException err) {
          System.out.println(err.getMessage());
                                         
    }//GEN-LAST:event_jButton6ActionPerformed
       }
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
       String first=jTextField1.getText();
       String second=jTextField2.getText();
       String third=jTextField3.getText();
       String fourth=jTextField4.getText();
       String fifth=jTextField5.getText();
       String sixth=jTextField6.getText();
       String id=jTextField7.getText();
       
       int newID= Integer.parseInt(id);
       
       try{
          rs.updateInt( "ID", newID );
              rs.updateString( "TipEveniment", first );
              rs.updateString( "LocEveniment", second );
              rs.updateString( "ZiuaEveniment", third );
              rs.updateString( "LunaEveniment", fourth );
              rs.updateString( "AnulEveniment", fifth );
              rs.updateString( "OraEveniment", sixth );
              rs.updateRow( );
            
       }
       catch(SQLException err) {
          System.out.println(err.getMessage());
    }                                        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
                // TODO add your handling code here:
           
        try{
            
            curRow=rs.getRow();
        
            jTextField7.setText(Integer.toString(rs.getInt("ID")));
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
        
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton8.setEnabled(false);
            jButton10.setEnabled(false);//update,delete, new record
            
            jButton6.setEnabled(true);//salvare
            jButton11.setEnabled(true);//cancel
    }//GEN-LAST:event_jButton10ActionPerformed
 catch(SQLException err) {
          System.out.println(err.getMessage());
 }
    }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try{
            rs.deleteRow();
            st.close();
            rs.close();
            st=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                                    ResultSet.CONCUR_UPDATABLE);
            String sql= "SELECT * from EVENIMENTE";
            rs=st.executeQuery(sql);
            
            rs.next();
            int id_col=rs.getInt("ID");
            String id=Integer.toString(id_col);
            String first=rs.getString("TipEveniment");
            String second=rs.getString("LocEveniment");
            String third=rs.getString("ZiuaEveniment");
            String fourth=rs.getString("LunaEveniment");
            String fifth=rs.getString("AnulEveniment");
            String sixth=rs.getString("OraEveniment");
            
            jTextField7.setText(id);
            jTextField1.setText(first);
            jTextField2.setText(second);
            jTextField3.setText(third);
            jTextField4.setText(fourth);
            jTextField5.setText(fifth);
            jTextField6.setText(sixth);     
        }
        catch(SQLException err) {
          System.out.println(err.getMessage());
 }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
          try{
            
            rs.absolute(curRow);
        
            jTextField7.setText(Integer.toString(rs.getInt("ID")));
            jTextField1.setText(rs.getString("TipEveniment"));
            jTextField2.setText(rs.getString("LocEveniment"));
            jTextField3.setText(rs.getString("ZiuaEveniment"));
            jTextField4.setText(rs.getString("LunaEveniment"));
            jTextField5.setText(rs.getString("AnulEveniment"));
            jTextField6.setText(rs.getString("OraEveniment"));
        
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton8.setEnabled(false);
            jButton10.setEnabled(false);//update,delete, new record
            
            jButton6.setEnabled(true);//salvare
            jButton11.setEnabled(true);//cancel
    }                                         
 catch(SQLException err) {
          System.out.println(err.getMessage());
 }
    }//GEN-LAST:event_jButton11ActionPerformed
                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FEveniment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FEveniment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FEveniment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FEveniment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FEveniment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}

