/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfete;

import Clasele.Persoana;
import static java.lang.System.err;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dya_Bia
 */
public class FPersoana extends javax.swing.JFrame {

    /**
     * Creates new form FPersoana
     */
      Connection con;
            Statement st;
            ResultSet rs;
            int cur = 0;
    private int curRow;
            
    public FPersoana() {
        initComponents();
           DoConnect();
    }
  public void DoConnect()
    {
        try{
            String host="jdbc:derby://localhost:1527/Georgiana";
            String uName="Georgiana";
            String uPass="55555";
            
         //  System.out.println("Urma1");
           Connection con=DriverManager.getConnection(host,uName, uPass);
            //System.out.println("Urma2");
           
            st=con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String sql="select * from PERSOANA";
            rs =st.executeQuery(sql);
            
            //rs.previous();
            rs.next();
            int id_col=rs.getInt("ID");
            String id= Integer.toString(id_col);
            String primul=rs.getString("NumePer");
            String doi=rs.getString("PrenumePer");
            String patru=rs.getString("Strada");
            String cinci=rs.getString("Numar");
            String sase=rs.getString("Bloc");
            String sapte=rs.getString("Scara");
            String opt=rs.getString("Apartament");
            String noua=rs.getString("Localitate");
            String zece=rs.getString("Judet");
            String unsprezece=rs.getString("Ziuanastere");
            String doisprezece=rs.getString("Lunanastere");
            String treisprezece=rs.getString("Anulnastere");
            String paisprezece=rs.getString("Telefon");
            String cincisprezece=rs.getString("Mail");
             String saisprezece=rs.getString("Etaj");
   
   
   
            jTextField16.setText(id);
            jTextField1.setText(primul);
            jTextField2.setText(doi);
            jTextField3.setText(patru);
            jTextField4.setText(cinci);
            jTextField5.setText(sase);
            jTextField6.setText(sapte);
            jTextField7.setText(opt);
            jTextField8.setText(noua);//label9
            jTextField9.setText(zece);
            jTextField10.setText(unsprezece);
            jTextField11.setText(doisprezece);
            jTextField12.setText(treisprezece);
            jTextField13.setText(paisprezece);
            jTextField14.setText(cincisprezece);
            jTextField15.setText(saisprezece);
            
            
        }
    catch( SQLException err){
           //JOptionPane.showMessageDialog(err.getMessage());
        System.out.println(err.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Nume persoana");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 30, 74, 13);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(108, 20, 200, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Prenume persoana");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 60, 88, 13);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(110, 50, 200, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Adresa");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 86, 44, 13);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Strada");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 86, 31, 13);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(110, 80, 200, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("Numar");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 120, 33, 13);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(110, 110, 200, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("Bloc");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 150, 21, 13);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(110, 140, 70, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("Scara");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(190, 150, 27, 13);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(243, 140, 60, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("Apartament");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 210, 60, 13);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(110, 200, 70, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("Localitate");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 240, 47, 13);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(110, 230, 200, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 153));
        jLabel10.setText("Judet");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(40, 260, 26, 20);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(110, 260, 200, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 3, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Ziua nastere");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 300, 58, 13);
        getContentPane().add(jTextField10);
        jTextField10.setBounds(110, 290, 200, 30);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 3, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Luna nastere");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(20, 330, 61, 13);
        getContentPane().add(jTextField11);
        jTextField11.setBounds(110, 320, 200, 30);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 3, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Anul nastere");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(20, 360, 58, 13);
        getContentPane().add(jTextField12);
        jTextField12.setBounds(110, 350, 200, 30);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 3, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Numar de telefon");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(10, 390, 81, 13);
        getContentPane().add(jTextField13);
        jTextField13.setBounds(110, 380, 200, 30);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 3, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Adresa de e-mail");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(10, 420, 79, 13);
        getContentPane().add(jTextField14);
        jTextField14.setBounds(110, 410, 200, 30);

        jButton8.setBackground(new java.awt.Color(204, 255, 255));
        jButton8.setFont(new java.awt.Font("Script MT Bold", 0, 11)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 0, 255));
        jButton8.setText("Primul");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(10, 460, 65, 23);

        jButton9.setBackground(new java.awt.Color(204, 255, 255));
        jButton9.setFont(new java.awt.Font("Script MT Bold", 0, 11)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 0, 255));
        jButton9.setText("Precedentul");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(100, 460, 83, 23);

        jButton10.setBackground(new java.awt.Color(204, 255, 255));
        jButton10.setFont(new java.awt.Font("Script MT Bold", 0, 11)); // NOI18N
        jButton10.setForeground(new java.awt.Color(0, 0, 255));
        jButton10.setText("Urmatorul");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(190, 460, 81, 23);

        jButton11.setBackground(new java.awt.Color(204, 255, 255));
        jButton11.setFont(new java.awt.Font("Script MT Bold", 0, 11)); // NOI18N
        jButton11.setForeground(new java.awt.Color(0, 0, 255));
        jButton11.setText("Ultimul");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(310, 460, 69, 23);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 255));
        jLabel16.setText("Etaj");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(70, 180, 19, 13);
        getContentPane().add(jTextField15);
        jTextField15.setBounds(110, 170, 70, 30);

        jLabel17.setText("ID");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(220, 0, 11, 14);

        jTextField16.setText(" ");
        getContentPane().add(jTextField16);
        jTextField16.setBounds(240, 0, 28, 20);

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("Script MT Bold", 0, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 490, 65, 23);

        jButton2.setBackground(new java.awt.Color(204, 255, 255));
        jButton2.setFont(new java.awt.Font("Script MT Bold", 0, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 255));
        jButton2.setText("Stergere");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(100, 490, 67, 23);

        jButton3.setBackground(new java.awt.Color(204, 255, 255));
        jButton3.setFont(new java.awt.Font("Script MT Bold", 0, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 255));
        jButton3.setText("New record");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(190, 490, 83, 23);

        jButton4.setBackground(new java.awt.Color(204, 255, 255));
        jButton4.setFont(new java.awt.Font("Script MT Bold", 0, 11)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 255));
        jButton4.setText("Salvare noua");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(290, 490, 93, 23);

        jButton5.setBackground(new java.awt.Color(204, 255, 255));
        jButton5.setFont(new java.awt.Font("Script MT Bold", 0, 11)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 255));
        jButton5.setText("Cancel");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(10, 520, 61, 23);

        jButton6.setBackground(new java.awt.Color(204, 255, 255));
        jButton6.setFont(new java.awt.Font("Script MT Bold", 0, 11)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 255));
        jButton6.setText("Terminare");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(300, 520, 77, 23);

        jLabel18.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(153, 0, 204));
        jLabel18.setText("Persoana");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(102, 0, 67, 24);

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dya_Bia\\Desktop\\people.jpg")); // NOI18N
        getContentPane().add(jLabel19);
        jLabel19.setBounds(0, 20, 390, 520);

        setSize(new java.awt.Dimension(407, 590));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        try
        {
            if(rs.next())
            {
               
        int id_col=rs.getInt("ID");
            String id= Integer.toString(id_col);
            String primul=rs.getString("NumePer ");
            String doi=rs.getString("PrenumePer");
            String patru=rs.getString("Strada");
            String cinci=rs.getString("Numar");
            String sase=rs.getString("Bloc");
            String sapte=rs.getString("Scara");
            String opt=rs.getString("Apartament");
            String noua=rs.getString("Localitate");
            String zece=rs.getString("Judet");
            String unsprezece=rs.getString("Ziuanastere");
            String doisprezece=rs.getString("Lunanastere");
            String treisprezece=rs.getString("Anulnastere");
            String paisprezece=rs.getString("Telefon");
            String cincisprezece=rs.getString("Mail");
             String saisprezece=rs.getString("Etaj");
   
   
   
            jTextField16.setText(id);
            jTextField1.setText(primul);
            jTextField2.setText(doi);
            jTextField3.setText(patru);
            jTextField4.setText(cinci);
            jTextField5.setText(sase);
            jTextField6.setText(sapte);
            jTextField7.setText(opt);
            jTextField8.setText(noua);//label9
            jTextField9.setText(zece);
            jTextField10.setText(unsprezece);
            jTextField11.setText(doisprezece);
            jTextField12.setText(treisprezece);
            jTextField13.setText(paisprezece);
            jTextField14.setText(cincisprezece);
            jTextField15.setText(saisprezece);
    }//GEN-LAST:event_jButton10ActionPerformed
      
          else
            {
                rs.previous();
            }    
        }
        catch(SQLException err) {
          System.out.println(err.getMessage());

}
}
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        try
        {
            if(rs.previous())
            {
            int id_col=rs.getInt("ID");
            String id= Integer.toString(id_col);
            String primul=rs.getString("NumePer");
            String doi=rs.getString("PrenumePer");
            String patru=rs.getString("Strada");
            String cinci=rs.getString("Numar");
            String sase=rs.getString("Bloc");
            String sapte=rs.getString("Scara");
            String opt=rs.getString("Apartament");
            String noua=rs.getString("Localitate");
            String zece=rs.getString("Judet");
            String unsprezece=rs.getString("Ziuanastere");
            String doisprezece=rs.getString("Lunanastere");
            String treisprezece=rs.getString("Anulnastere");
            String paisprezece=rs.getString("Telefon");
            String cincisprezece=rs.getString("Mail");
             String saisprezece=rs.getString("Etaj");
   
   
   
            jTextField16.setText(id);
            jTextField1.setText(primul);
            jTextField2.setText(doi);
            jTextField3.setText(patru);
            jTextField4.setText(cinci);
            jTextField5.setText(sase);
            jTextField6.setText(sapte);
            jTextField7.setText(opt);
            jTextField8.setText(noua);//label9
            jTextField9.setText(zece);
            jTextField10.setText(unsprezece);
            jTextField11.setText(doisprezece);
            jTextField12.setText(treisprezece);
            jTextField13.setText(paisprezece);
            jTextField14.setText(cincisprezece);
            jTextField15.setText(saisprezece);
    }                                         
       
          else
            {
                rs.next();
            }    
        }
        
        catch(SQLException err) {
          System.out.println(err.getMessage());

}

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        try{
            rs.first();
            int id_col=rs.getInt("ID");
            String id= Integer.toString(id_col);
            String primul=rs.getString("NumePer");
            String doi=rs.getString("PrenumePer");
            String patru=rs.getString("Strada");
            String cinci=rs.getString("Numar");
            String sase=rs.getString("Bloc");
            String sapte=rs.getString("Scara");
            String opt=rs.getString("Apartament");
            String noua=rs.getString("Localitate");
            String zece=rs.getString("Judet");
            String unsprezece=rs.getString("Ziuanastere");
            String doisprezece=rs.getString("Lunanastere");
            String treisprezece=rs.getString("Anulnastere");
            String paisprezece=rs.getString(" Telefon");
            String cincisprezece=rs.getString("Mail");
            String saisprezece=rs.getString("Etaj");
   
   
   
            jTextField16.setText(id);
            jTextField1.setText(primul);
            jTextField2.setText(doi);
            jTextField3.setText(patru);
            jTextField4.setText(cinci);
            jTextField5.setText(sase);
            jTextField6.setText(sapte);
            jTextField7.setText(opt);
            jTextField8.setText(noua);//label9
            jTextField9.setText(zece);
            jTextField10.setText(unsprezece);
            jTextField11.setText(doisprezece);
            jTextField12.setText(treisprezece);
            jTextField13.setText(paisprezece);
            jTextField14.setText(cincisprezece);
            jTextField15.setText(saisprezece);
        }
        catch(SQLException err) {
          System.out.println(err.getMessage());

       }                                         
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        try{
            rs.last();
            int id_col=rs.getInt("ID");
            String id= Integer.toString(id_col);
            String primul=rs.getString("NumePer");
            String doi=rs.getString("PrenumePer");
            String patru=rs.getString("Strada");
            String cinci=rs.getString("Numar");
            String sase=rs.getString("Bloc");
            String sapte=rs.getString("Scara");
            String opt=rs.getString("Apartament");
            String noua=rs.getString("Localitate");
            String zece=rs.getString("Judet");
            String unsprezece=rs.getString("Ziuanastere");
            String doisprezece=rs.getString("Lunanastere");
            String treisprezece=rs.getString("Anulnastere");
            String paisprezece=rs.getString("Telefon");
            String cincisprezece=rs.getString("Mail");
            String saisprezece=rs.getString("Etaj");
   
   
   
            jTextField16.setText(id);
            jTextField1.setText(primul);
            jTextField2.setText(doi);
            jTextField3.setText(patru);
            jTextField4.setText(cinci);
            jTextField5.setText(sase);
            jTextField6.setText(sapte);
            jTextField7.setText(opt);
            jTextField8.setText(noua);//label9
            jTextField9.setText(zece);
            jTextField10.setText(unsprezece);
            jTextField11.setText(doisprezece);
            jTextField12.setText(treisprezece);
            jTextField13.setText(paisprezece);
            jTextField14.setText(cincisprezece);
            jTextField15.setText(saisprezece);
        }
        catch(SQLException err) {
          System.out.println(err.getMessage());

       }  
            
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         try{
            
            rs.absolute(curRow);
             jTextField16.setText(Integer.toString(rs.getInt("ID")));
            jTextField1.setText(" ");
            jTextField2.setText(" ");
            jTextField3.setText(" ");
            jTextField4.setText(" ");
            jTextField5.setText(" ");
            jTextField6.setText(" ");
            jTextField7.setText(" ");
            jTextField8.setText(" ");//label9
            jTextField9.setText( " ");
            jTextField10.setText(" ");
            jTextField11.setText(" ");
            jTextField12.setText(" ");
            jTextField13.setText( " ");
            jTextField14.setText(" ");
            jTextField15.setText(" ");
            
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton11.setEnabled(false);
            jButton9.setEnabled(false);
            jButton8.setEnabled(false);
            jButton10.setEnabled(false);//update,delete, new record
            
            jButton4.setEnabled(true);//salvare
            jButton5.setEnabled(true);//cancel
         }
         catch(SQLException err) {
          System.out.println(err.getMessage());
 }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String primul=jTextField1.getText();
        String doi=jTextField2.getText();    
        String patru =jTextField3.getText();  
        String cinci=jTextField14.getText();  
        String sase=jTextField5.getText();  
        String sapte=jTextField6.getText();  
        String opt=jTextField7.getText();  
        String noua=jTextField8.getText();  
        String zece=jTextField9.getText();  
        String unsprezece=jTextField10.getText();  
        String doisprezece=jTextField11.getText();  
        String treisprezece=jTextField12.getText();  
        String paisprezece= jTextField13.getText();  
        String cincisprezece=jTextField14.getText();  
        String saisprezece=jTextField15.getText();  
        
        String id=jTextField16.getText();
         int newID= Integer.parseInt(id);
         
       try {
           rs.moveToInsertRow();
           
              rs.updateInt( "ID", newID );
              rs.updateString( "NumePer", primul );
              rs.updateString("Strada", patru);
              rs.updateString( "Numar",cinci );
              rs.updateString( "Bloc", sase);
              rs.updateString( "Scara", sapte );
              rs.updateString( "Apartament", opt );
              rs.updateString("Localitate" , noua );
              rs.updateString( "Judet", zece );
              rs.updateString( "Ziuanastere",unsprezece );
              rs.updateString( "Lunanastere",doisprezece);
              rs.updateString( "Anulnastere" ,treisprezece);
              rs.updateString( "Telefon" ,paisprezece);
              rs.updateString(  "Mail",cincisprezece);
              rs.updateString( "Etaj" ,saisprezece);
              rs.updateRow( );
              
              rs.insertRow();
              
              st.close();
              rs.close();
              st=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                                    ResultSet.CONCUR_UPDATABLE);
              String sql= "SELECT * from PERSOANA";
             rs = st.executeQuery(sql);
             
              rs.next();
             int id_col=rs.getInt("ID");
      // String id= Integer.toString(id_col);
            String primul1=rs.getString("NumePer");
            String doi1=rs.getString("PrenumePer");
            String patru1=rs.getString("Strada");
            String cinci1=rs.getString("Numar");
            String sase1=rs.getString("Bloc");
            String sapte1=rs.getString("Scara");
            String opt1=rs.getString("Apartament");
            String noua1=rs.getString("Localitate");
            String zece1=rs.getString("Judet");
            String unsprezece1=rs.getString("Ziuanastere");
            String doisprezece1=rs.getString("Lunanastere");
            String treisprezece1=rs.getString("Anulnastere");
            String paisprezece1=rs.getString("Telefon");
            String cincisprezece1=rs.getString("Mail");
            String saisprezece1=rs.getString("Etaj");
   
   
   
            jTextField16.setText(id);
            jTextField1.setText(primul1);
            jTextField2.setText(doi1);
            jTextField3.setText(patru1);
            jTextField4.setText(cinci1);
            jTextField5.setText(sase1);
            jTextField6.setText(sapte1);
            jTextField7.setText(opt1);
            jTextField8.setText(noua1);
            jTextField9.setText(zece1);
            jTextField10.setText(unsprezece1);
            jTextField11.setText(doisprezece1);
            jTextField12.setText(treisprezece1);
            jTextField13.setText(paisprezece1);
            jTextField14.setText(cincisprezece1);
            jTextField15.setText(saisprezece1);
         
       jButton1.setEnabled(true);
       jButton2.setEnabled(true);
       jButton3.setEnabled(true);
       jButton11.setEnabled(true);
       jButton8.setEnabled(true);
       jButton9.setEnabled(true);
       jButton10.setEnabled(true);
       
       jButton5.setEnabled(false);
       jButton4.setEnabled(false);
            }
    
    
        catch(SQLException err) {
          System.out.println(err.getMessage());
                                         
    }            
                
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String primul=jTextField1.getText();
        String doi=jTextField2.getText();    
        String patru =jTextField3.getText();  
        String cinci=jTextField14.getText();  
        String sase=jTextField5.getText();  
        String sapte=jTextField6.getText();  
        String opt=jTextField7.getText();  
        String noua=jTextField8.getText();  
        String zece=jTextField9.getText();  
        String unsprezece=jTextField10.getText();  
        String doisprezece=jTextField11.getText();  
        String treisprezece=jTextField12.getText();  
        String paisprezece= jTextField13.getText();  
        String cincisprezece=jTextField14.getText();  
        String saisprezece=jTextField15.getText();  
        
        String id=jTextField16.getText();
         int newID= Integer.parseInt(id);
         try{
          rs.updateInt( "ID", newID );
            rs.updateInt( "ID", newID );
              rs.updateString( "NumePer", primul );
              rs.updateString("Strada", patru);
              rs.updateString( "Numar",cinci );
              rs.updateString( "Bloc", sase);
              rs.updateString( "Scara", sapte );
              rs.updateString( "Apartament", opt );
              rs.updateString("Localitate" , noua );
              rs.updateString( "Judet", zece );
              rs.updateString( "Ziuanastere",unsprezece );
              rs.updateString( "Lunanastere",doisprezece);
              rs.updateString( "Anulnastere" ,treisprezece);
              rs.updateString( "Telefon" ,paisprezece);
              rs.updateString(  "Mail",cincisprezece);
              rs.updateString( "Etaj" ,saisprezece);
              rs.updateRow( );
          
       
    jButton1.setEnabled(false);
       jButton2.setEnabled(false);
       jButton3.setEnabled(false);
       jButton4.setEnabled(false);
       jButton8.setEnabled(false);
       jButton5.setEnabled(false);
       jButton10.setEnabled(false);
       
       jButton6.setEnabled(true);
       jButton11.setEnabled(true);
          }
       catch(SQLException err) {
          System.out.println(err.getMessage());
    }         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            rs.deleteRow();
            st.close();
            rs.close();
            st=con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                                    ResultSet.CONCUR_UPDATABLE);
            String sql= "SELECT * from PERSOANA";
            
            rs=st.executeQuery(sql);
            int id_col=rs.getInt("ID");
            String id= Integer.toString(id_col);
            String primul=rs.getString("NumePer");
            String doi=rs.getString("PrenumePer");
            String patru=rs.getString("Strada");
            String cinci=rs.getString("Numar");
            String sase=rs.getString("Bloc");
            String sapte=rs.getString("Scara");
            String opt=rs.getString("Apartament");
            String noua=rs.getString("Localitate");
            String zece=rs.getString("Judet");
            String unsprezece=rs.getString("Ziuanastere");
            String doisprezece=rs.getString("Lunanastere");
            String treisprezece=rs.getString("Anulnastere");
            String paisprezece=rs.getString("Telefon");
            String cincisprezece=rs.getString("Mail");
            String saisprezece=rs.getString("Etaj");
   
            jTextField16.setText(id);
            jTextField1.setText(primul);
            jTextField2.setText(doi);
            jTextField3.setText(patru);
            jTextField4.setText(cinci);
            jTextField5.setText(sase);
            jTextField6.setText(sapte);
            jTextField7.setText(opt);
            jTextField8.setText(noua);//label9
            jTextField9.setText(zece);
            jTextField10.setText(unsprezece);
            jTextField11.setText(doisprezece);
            jTextField12.setText(treisprezece);
            jTextField13.setText(paisprezece);
            jTextField14.setText(cincisprezece);
            jTextField15.setText(saisprezece);
            rs.next();
             }
        catch(SQLException err) {
          System.out.println(err.getMessage());
 }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
            
            curRow=rs.getRow();
            jTextField16.setText(Integer.toString(rs.getInt("ID")));
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField10.setText("");
            jTextField11.setText("");
            jTextField12.setText("");
            jTextField13.setText("");
            jTextField14.setText("");
            jTextField15.setText("");
            
             jButton8.setEnabled(false);
            jButton9.setEnabled(false);
            jButton10.setEnabled(false);
            jButton11.setEnabled(false);
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);//update,delete, new record
            
            jButton4.setEnabled(true);//salvare
            jButton5.setEnabled(true);//cancel
         }                                         
 catch(SQLException err) {
          System.out.println(err.getMessage());
 }
    }//GEN-LAST:event_jButton3ActionPerformed
 
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
